algeria:
  name: Algeria

argentina:
  name: Argentina

australia:
  name: Australia

belgium:
  name: Belgium

bosnia-and-herzegovina:
  name: Bosnia and Herzegovina

brazil:
  name: Brazil

cameroon:
  name: Cameroon

chile:
  name: Chile

colombia:
  name: Colombia

costa-rica:
  name: Costa Rica

cote-divoire:
  name: Côte d'Ivoire

croatia:
  name: Croatia

ecuador:
  name: Ecuador

england:
  name: England

france:
  name: France

germany:
  name: Germany

ghana:
  name: Ghana

greece:
  name: Greece

honduras:
  name: Honduras

iran:
  name: Iran

italy:
  name: Italy

japan:
  name: Japan

korea-republic:
  name: Korea Republic

mexico:
  name: Mexico

netherlands:
  name: Netherlands

nigeria:
  name: Nigeria

portugal:
  name: Portugal

russia:
  name: Russia

spain:
  name: Spain

switzerland:
  name: Switzerland

united-states:
  name: United States

uruguay:
  name: Uruguay
